---
- name: master server
  hosts: control_plane
  roles:
    - role: preconfig
      tag: preconfig
    - role: installing_kubectl
      tag: installing_kubectl
    - role: flannel
      tag: flannel

- name: workers servers
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig